logging:
  added_loggers:
  - rosbag
  auto: true
  base_dir: /home/mavis
  data_dir: /home/mavis/user_018
  rosbag:
    enabled: false
    topics: []
teleop:
  modes:
  - &id001
    filename: controls_spec.yaml
    logging:
      added_loggers:
      - rosbag
      auto: true
      base_dir: /home/mavis
      data_dir: /home/mavis/user_018
      rosbag:
        enabled: false
        topics: []
    teleop:
      modes:
      - axes:
        - deadzone: 0.0
          output: AXIS_X
          scale: -1.0
        - deadzone: 0.0
          output: AXIS_Y
          scale: -1.0
        - deadzone: 0.0
          output: ''
          scale: 1.0
        - deadzone: 0.0
          output: ''
          scale: 1.0
        - deadzone: 0.0
          output: AXIS_Z
          scale: 1.0
        - deadzone: 0.0
          output: ''
          scale: 1.0
        - deadzone: 0.0
          output: AXIS_YAW
          scale: 1.0
        - deadzone: 0.0
          output: AXIS_ROLL
          scale: 1.0
        buttons:
        - output: ''
        - output: ''
        - output: ''
        - output: ''
        - output: CLOSE_GRIPPER
        - output: OPEN_GRIPPER
        - output: ''
        - output: ''
        - output: ''
        - output: ''
        - output: ''
        - output: ''
        - output: ''
        filename: controls_spec.yaml
      plugin: gen2
  - *id001
  plugin: gen2
