axes:
  - deadzone: 0.0
    output: AXIS_X
    scale: -1.0
  - deadzone: 0.0
    output: AXIS_Y
    scale: -1.0
  - deadzone: 0.0
    output: ''
    scale: 1.0
  - deadzone: 0.0
    output: ''
    scale: 1.0
  - deadzone: 0.0
    output: 'AXIS_Z'
    scale: 1.0
  - deadzone: 0.0
    output: ''
    scale: 1.0
  - deadzone: 0.0
    output: 'AXIS_YAW'
    scale: 1.0
  - deadzone: 0.0
    output: 'AXIS_ROLL'
    scale: 1.0
buttons:
  - output: ''
  - output: ''
  - output: ''
  - output: ''
  - output: 'CLOSE_GRIPPER'
  - output: ''
  - output: 'OPEN_GRIPPER'
  - output: ''
  - output: ''
  - output: ''
  - output: ''
  - output: ''
  - output: ''
